version: '3'

services:
  mysqlsrv:
    image: mysql:8.0.27
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${TYPEORM_PASSWORD}
      MYSQL_DATABASE: ${TYPEORM_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - /config/db
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8088:8080
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge